version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: alumni_mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: alumni_management
    volumes:
      - mongodb_data:/data/db
    networks:
      - alumni_network

networks:
  alumni_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
